### ISSUE TITLE
_build_model()

### ISSUE THREAD

**Issue by jbachh** [imdatsolak/keras2-wavenet#5]
In mlwavenet.py's _build_model()
`if not self.learn_all_outputs:
            raise DeprecationWarning('Learning on just all outputs is wasteful, now learning only inside receptive field.')
out = layers.Lambda(lambda x: x[:, -1, :], output_shape=(out._keras_shape[-1],))(out) # Based on gif in deepmind blog: take last output?`

you better do this before the two final 1x1 convolutional layers a few lines above to cut more waste, right?

**Comment by imdatsolak** [comment]
@jbachh, I guess it should actually be before the skip_connections (layers.Add(...)). Have you tried it out? From the paper, it seems the learning on only receptive field should be **after** the stacks...

**Comment by jbachh** [comment]
Haven't tried it out yet, I am in the beginning of my own implementation. Thanks for the links, will check it out.
